### ISSUE TITLE
How to Make Realtime Notifications in Laravel Sanctum (SPA) - Private Channel Broadcasting ?

### ISSUE THREAD

**Issue by joneyspark** [kritish-dhaubanjar/laravel-websockets-sanctum#1] opened 2021-06-23 16:53 UTC
Hi, I am using Laravel -v7.x and Vue CLI two different folders for Frontend and Backend. And using Laravel Sanctum (SPA) Authentication. I want to create real-time Notifications when some Events happen in my backend. and I already configured successfully the Websockets and the public Broadcasting working fine. But when I'm trying to using PrivateChannel then backend WebSockets can run the event on the WebSockets panel I see but could not get response on the console. Can you please help me? Below I share my code.

Vue CLI
---------------
#main.js

```js

<script>
import Request from "./apis/Request"
import Echo from 'laravel-echo';
window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.VUE_APP_WEBSOCKETS_KEY,
    wsHost: process.env.VUE_APP_WEBSOCKETS_SERVER,
    encrypted: true,
    cluster: 'ap1',
    wsPort: 6001,
    forceTLS: false,
    disableStats: true,
    authorizer: (channel, options) => {
        console.log("OPTIONS>>", options);
        return {
            authorize: (socketId, callback) => {
                Request.POST_REQ('/broadcasting/auth', {
                    socket_id: socketId,
                    channel_name: channel.name
                })
                .then(response => {
                    callback(false, response.data);
                    console.log("RESPONSE>>", response);
                })
                .catch(error => {
                    callback(true, error);
                });
            }
        };
    },
})
</script>

```
#App.vue

```js

<script>
import { mapGetters } from "vuex";
export default {
    computed: {
    ...mapGetters(["user"])
  },
    async mounted() {
        await window.Echo.private(`hello.user.${this.user.id}`).listen(
      "Hello",
      () => {
        console.log("OK");
      }
    );
    },
}
</script>

```

#vue env
--------
#.env

```
VUE_APP_WEBSOCKETS_KEY = local
VUE_APP_WEBSOCKETS_SERVER = localhost

```

#Laravel

#Hello Event

#Hello.php

```php

<?php

namespace App\Events;

use Illuminate\Broadcasting\Channel;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

class Hello implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public function __construct()
    {
        //
    }

    public function broadcastWith()
    {
        return [
            'hello' => 'Hello world'
        ];
    }

    public function broadcastOn()
    {
        return new PrivateChannel('hello.user.1');
    }
}

```

#BroadcastServiceProvider.php

```php

<?php

namespace App\Providers;
use Illuminate\Support\Facades\Broadcast;
use Illuminate\Support\ServiceProvider;

class BroadcastServiceProvider extends ServiceProvider
{
    public function boot()
    {
        // Broadcast::routes();
        Broadcast::routes(["middleware" => ["auth:sanctum"]]);

        require base_path('routes/channels.php');
    }
}

```

#channels.php

```php

<?php

use Illuminate\Support\Facades\Broadcast;

Broadcast::channel('hello.user.{id}', function ($user, $id) {
    return (int) $user->id === (int) $id;
});

```

#laravel env
--------
#.env

```
PUSHER_APP_ID=local
PUSHER_APP_KEY=local
PUSHER_APP_SECRET=local
PUSHER_APP_CLUSTER=ap1

```

#broadcasting.php

```php

<?php

return [

'default' => env('BROADCAST_DRIVER', 'pusher'),

'connections' => [

        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true,
                'encrypted' => true,
                'host' => 'localhost',
                'port' => 6001,
                'scheme' => 'http'
            ],
        ],
    ],
];

```
#I run the event using tinker
--------------------------------------

`php artisan tinker`

`event(new App\Events\Hello())`

**Comment by kritish-dhaubanjar** [comment] 2021-07-15 07:31
Sorry for the late reply, I'm confused with few things in this implementation...
1. Have you passed the authorization token to `/broadcasting/auth`, I see you're using your own util for this.

Here's a working snippet for the Private channel...

```php
class NewMessage implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $payload;
    public $recipient;
    public $sender;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($payload, $recipient, $sender)
    {
        $this->payload = $payload;
        $this->recipient = $recipient;
        $this->sender = $sender;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new PrivateChannel('App.Models.User.' . $this->recipient->id);
    }

    public function broadcastAs()
    {
        return 'new-message-event';
    }
}
```

Dispatched using 
```php
NewMessage::dispatch($message, $user, $sender);
```

And Vue SPA as

```js
        this.echo = new Echo({
          broadcaster: 'pusher',
          key: process.env.pusherKey,
          cluster: 'ap2',
          authorizer: (channel, options) => {
            // console.log(options);
            return {
              authorize: (socketId, callback) => {
                axios({
                  method: 'POST',
                  url: process.env.authEndPoint,
                  headers: {
                    Authorization: `Bearer ${this.$store.state.accessToken}`
                  },
                  data: {
                    socket_id: socketId,
                    channel_name: channel.name
                  }
                })
                  .then(response => {
                    callback(false, response.data);
                  })
                  .catch(error => {
                    callback(true, error);
                  });
              }
            };
          }

     ...


     this.echo
          .private(`App.Models.User.${user.id}`)
          .listen('.new-message-event', data => {
            // console.log(data);
            this.$eventBus.$emit('new-message-e', data);
          });
      }
```

**Comment by joneyspark** [comment] 2021-07-15 08:45
@kritish-dhaubanjar I'm glad to see your reply. Actually, I'm not using Token-based Sanctum. I'm using Sanctum - SPA Authentication cookie-based. And I'm following the private broadcasting laravel doc : https://laravel.com/docs/7.x/sanctum#authorizing-private-broadcast-channels

but I don't know it's not working at all and I saw a lot of developers also ask this question but not getting the proper answer I'm confused its a Laravel bug or I am not sure Actually

**Comment by kritish-dhaubanjar** [comment] 2021-07-15 10:56
@joneyspark, For Cookie based SPA Auth, it should work if you've configured all the middlewares correctly, 
I see you're using `Broadcast::routes(["middleware" => ["auth:api"]]);` which won't work if your SPA is authenticating via Sanctum.
`Broadcast::routes(['middleware' => ['auth:sanctum']]);` is the one that recognizes the authenticated requests ...

I had tried this earlier when sanctum was released as airlock, however I had difficulties to getting it to work then, I have not tried it since, may be give it a try in my spare time...

**Comment by joneyspark** [comment] 2021-07-15 11:01
@kritish-dhaubanjar Thanks for your suggestions but I might forget to update my code in here. I tried many times to `Broadcast::routes(['middleware' => ['auth:sanctum']]);` change it but the problem is when using private broadcasting it's might laravel can not recognize the authenticate user. I am already trying but not working at all

**Comment by kritish-dhaubanjar** [comment] 2021-07-15 16:21
@joneyspark I prepared a repo configuring SPA with laravel sanctum & websockets [here](https://github.com/kritish-dhaubanjar/laravel-sanctum-websockets-spa). Will create a README.md explaining the stuffs.

**Comment by joneyspark** [comment] 2021-07-15 16:29
Hey, @kritish-dhaubanjar that's Great. I really thankful to you :heart:

**Comment by kritish-dhaubanjar** [comment] 2021-07-15 16:45
No Worries @joneyspark, Please do raise an issue if the instructions don't work as intended, Happy to help!....

**Comment by joneyspark** [comment] 2021-07-15 16:48
@kritish-dhaubanjar Thanks a lot. I have a question have you work with Facebook API - Leads Integration with Custom CRM before ?

**Comment by kritish-dhaubanjar** [comment] 2021-07-15 16:52
@joneyspark Nope :sweat_smile: , Haven't worked with Facebook API at all......¯\_(ツ)_/¯

**Closed as completed** 2021-07-15 16:55 UTC
Labels: question
